### ISSUE TITLE
目标框中指定的名称无效

### ISSUE THREAD

**Issue by cakvfcwz** [VergilGao/RunAsInvoker#1]

**Comment by VergilGao** [comment]
没太看懂什么意思？有更详细的信息吗？

**Comment by cakvfcwz** [comment]
> 没太看懂什么意思？有更详细的信息吗？

<img width="419" alt="屏幕截图 2024-03-17 143133" src="https://github.com/VergilGao/RunAsInvoker/assets/3722623/fb4b08a4-b220-4aed-bfa0-64414e563d74">
地址试了很多次都是这样

**Comment by VergilGao** [comment]
> > 没太看懂什么意思？有更详细的信息吗？
> 
> <img width="419" alt="屏幕截图 2024-03-17 143133" src="https://github.com/VergilGao/RunAsInvoker/assets/3722623/fb4b08a4-b220-4aed-bfa0-64414e563d74">
> 地址试了很多次都是这样


你目标栏是怎么填的

**Comment by cakvfcwz** [comment]
> > > 没太看懂什么意思？有更详细的信息吗？
> > 
> > 
> > <img alt="屏幕截图 2024-03-17 143133" width="419" src="https://private-user-images.githubusercontent.com/3722623/313450392-fb4b08a4-b220-4aed-bfa0-64414e563d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Njg4MjgsIm5iZiI6MTcxMDY2ODUyOCwicGF0aCI6Ii8zNzIyNjIzLzMxMzQ1MDM5Mi1mYjRiMDhhNC1iMjIwLTRhZWQtYmZhMC02NDQxNGU1NjNkNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTdUMDk0MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVlZTJiNDRiZDZhMmZiOWFmNGNhZTQwMjA5ZDg0YmRlNDU3YjFlM2ZkZmE5ZGZlNjg5OGEyYmRkMDllZTc5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TJ7jWwgjIhNW31QWXRET9ivZF0GjYtU3KnDtaceBjf0">
> > 地址试了很多次都是这样
> 
> 你目标栏是怎么填的

就是按readme说的在原来的地址前面加入"%地址% "，空格和英文双引号都有，我还试了两段放同一个双引号里面、空格放中间等形式，都是非法

**Comment by VergilGao** [comment]
你完整的路径怎么填的？

**Comment by cakvfcwz** [comment]
> 你完整的路径怎么填的？

"D:\Program Files\RunAsInvoker.exe ""D:\Star Rail\launcher.exe"

**Comment by VergilGao** [comment]
```"D:\Program Files\RunAsInvoker.exe " "D:\Star Rail\launcher.exe"```
这样，两个命令之间要加个空格。

**Comment by cakvfcwz** [comment]
OK了
